### ISSUE TITLE
How to compile a Haskell module

### ISSUE THREAD

**Issue by Jan129** [mchakravarty/language-c-inline#52]
Sorry for this stupid question. I want to use inline objc classes in my Haskell program. Suppose I have done it in a file Main.hs. Can you explain how I have to compile it with ghc to obtain an executable function main. I am a bit confused: how to use the objc compiler?

**Comment by mchakravarty** [comment]
Have a look at the Makefiles of the various example applications of language-c-inline from https://github.com/mchakravarty/language-c-inline/tree/master/tests/objc

These Makefiles call both GHC as well as the ObjC compiler (clang) using the appropriate command line arguments.
